name: Flutter CI

on: pull_request

jobs:
  checkout_flutter:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter format .

      - run: flutter format --set-exit-if-changed .
        id: unit_test
      - run: flutter test

  comment:
    needs: checkout_flutter
    name: Comment Result
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pull_request.createComment({
              pull_request_number: context.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Automated Unit Test Result: "${{ steps.unit_test.output }}"'
            })