name: Flutter CI

on: pull_request

jobs:
  checkout_flutter:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter format .

      - name: Running Flutter Test
        id: unit_test
        run: flutter test
        continue-on-error: true

  comment:
    needs: checkout_flutter
    name: Comment Result
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Automated Unit Test Result: "${{ needs.checkout_flutter.steps.unit_test.outputs }}"'
            })